### ISSUE TITLE
Bug: Code block file titles are no longer rendering correctly

### ISSUE THREAD

**Issue by meganesu** [meganesu/personal-site-v2#94]
## Background

This is what they should look like:
![Code block component, with a file title rendering above the code snippet](https://user-images.githubusercontent.com/3609989/213839588-0fe69aec-8c59-4324-847e-26ca6c137c14.png)

And this is what they're currently rendering as:
<img width="798" alt="Screen Shot 2023-01-20 at 6 19 19 PM" src="https://user-images.githubusercontent.com/3609989/213839630-2b4563b6-4719-4a7d-ad15-1f978d281543.png">

This might have happened as part of the Gatsby v5 migration (which updates to MDX v2)

## Resources

- [MDX Docs: Syntax highlighting with the `meta` field](https://mdxjs.com/guides/syntax-highlighting/#syntax-highlighting-with-the-meta-field)

**Comment by meganesu** [comment]
Fix: requires `remark-mdx-code-meta` plugin, to give access to the meta string (info string) on a code fence.

Problem: Run into a Gatsby error when adding the `remark-mdx-code-meta` plugin to the `gatsby-config.js`:
> Error: [ERR_REQUIRE_ESM]: require() of ES Module <PATH>/per
  sonal-site-v2/node_modules/remark-mdx-code-meta/index.js from <PATH>/personal-site-v2/gatsby-config.js not supported.
  Instead change the require of index.js in <PATH>/personal-s
  ite-v2/gatsby-config.js to a dynamic import() which is available in all CommonJS modules.

Source: https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/
> Please Note: Most of the remark ecosystem is ESM which means that packages like remark-gfm currently don’t work out of the box with Gatsby.

**Comment by meganesu** [comment]
## Error: "Jest encountered an unexpected token", "SyntaxError: Unexpected token 'export'"
```sh
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/megansullivan/Documents/personal-projects/personal-site-v2/node_modules/@mdx-js/mdx/index.js:7
    export {createProcessor} from './lib/core.js'
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      3 |
      4 | import * as runtime from 'react/jsx-runtime'
    > 5 | import { evaluate } from "@mdx-js/mdx"
        | ^
      6 |
      7 | import CodeBlock from "."
      8 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)
      at Object.<anonymous> (src/components/code-block/index.test.js:5:1)
```

### Why is this happening?

By default, Jest won't transform files in node_modules (like `@mdx-js/mdx`). But since I'm importing the `evaluate` method from `@mdx-js/mdx`, I need to also run it through the transpiler.

**First attempt to fix** (didn't work): Add `node_modules/@mdx-js/mdx` to the Jest config `transformIgnorePatterns` object.

**Problem:** There's a super long chain of node_modules to be added to `transformIgnorePatterns`. Adding `@mdx-js/mdx` to that array works, but then there's another node_module that `@mdx-js/mdx` calls, which also needs to get transformed. I tried adding them all to the regex string, but it started getting really long, and I never reached the end of it.
- I tried setting the `transformIgnorePatterns` string to `["(?!(node_modules))"]`, but that didn't work. It does transform everything in node_modules, but then it ignores everything *not* in node_modules (including the `setup-test-env.js` file, which needs to also be transformed).

**Question:** Is there a better way to tell Jest to transform all the node_modules *and* all the .js/.jsx files in the root directory? Or to recursively tell it to transform `@mdx-js/mdx` and all of the modules it calls?
- Yes! Use `esbuild` to convert the `@mdx-js/mdx` node_module from ESM to CommonJS. Noted in the docs on [Troubleshooting MDX](https://mdxjs.com/docs/troubleshooting-mdx/#esm):
    ```sh
    # With [esbuild](https://esbuild.github.io), this bundles the ESM package `@mdx-js/mdx` as CJS in `vendor/mdx.js`:
    npx esbuild @mdx-js/mdx --bundle --platform=node --outfile=vendor/mdx.js
    ```

**Actual fix:**
1. Use esbuild command above to bundle `@mdx-js/mdx` as CommonJS in `vendor/mdx.js`.
2. In test, update the `evaluate` import in the test file to use the version from `vendors/mdx.js` instead of `@mdx-js/mdx`:  
	```js
	import { evaluate } from "../../../vendor/mdx"`
	```
